CREATE TABLE tbl_cadfun (
CodFun INTEGER IDENTITY PRIMARY KEY,
Nome VARCHAR(40) NOT NULL,
Depto CHAR(2),
Funcao CHAR(20),
Salario DECIMAL(10,2)
)
ALTER TABLE tbl_cadfun
ALTER COLUMN Funcao VARCHAR (30); 

INSERT INTO tbl_cadfun 
(NOME, DEPTO, FUNCAO, SALARIO)
VALUES 
('CARLOS ALBERTO', '3', 'VENDEDOR', 1530.00),
('MARCOS HENRIQUE', '2', 'GERENTE', 8500.00),
('APARECIDA DA SILVA', '3', 'SECRETARIA', 1350.00),
('BRUNA MARQUEZINE', '4', 'ANALISTA', 3500.00),
('BRUNO DE OLIVEIRA', '1', 'ESTAGIÁRIO', 1200.00),
('ADRIANO DOS REIS', '2', 'VENDEDOR', 1530.00),
('CAUÃ ROCHA', '3', 'VENDEDOR', 1530.00),
('LIZ DE CASTRO', '4', 'VENDEDOR', 1530.00),
('GUSTAVO FERREIRA', '1', 'SECRETARIA', 1350.00),
('MARTHA ANTUNES', '2', 'ANALISTA', 3500.00),
('KAIQUE CARDOSO', '3', 'ESTAGIÁRIO', 1200.00),
('THIAGO MENDES', '4', 'VENDEDOR', 1530.00),
('ISABELLY FONSECA', '1', 'VENDEDOR', 1730.00),
('ALANA CARDOSO', '2', 'VENDEDOR', 1530.00),
('ESTHER DE CARVALHO', '3', 'SECRETARIA', 1350.00),
('MICHAEL MENDES', '4', 'ANALISTA', 3500.00),
('JULIA PINTO', '1', 'ESTAGIÁRIO', 1200.00),
('BÁRBARA FERNANDES', '2', 'VENDEDOR', 1530.00),
('LUIS NEVES', '3', 'VENDEDOR', 1530.00),
('THEO TEIXEIRA', '4', 'VENDEDOR', 1530.00);

SELECT * FROM tbl_cadfun

SELECT NOME, FUNCAO 
FROM tbl_cadfun

SELECT NOME, FUNCAO 
FROM tbl_cadfun
WHERE DEPTO = '1';

SELECT NOME, FUNCAO 
FROM tbl_cadfun
WHERE DEPTO = '2';

SELECT NOME, FUNCAO 
FROM tbl_cadfun
WHERE DEPTO = '3';

SELECT NOME, FUNCAO 
FROM tbl_cadfun
WHERE DEPTO = '4';

SELECT NOME, FUNCAO, SALARIO 
FROM tbl_cadfun
WHERE SALARIO > '1500.00';

SELECT NOME, FUNCAO, SALARIO 
FROM tbl_cadfun
WHERE SALARIO < '1500.00';

SELECT NOME, FUNCAO, SALARIO
FROM tbl_cadfun
WHERE SALARIO > '1500.00' AND DEPTO = '1';

SELECT * FROM tbl_cadfun
ORDER BY SALARIO ASC;

SELECT * FROM tbl_cadfun
ORDER BY SALARIO DESC;

DELETE FROM tbl_cadfun
WHERE CodFun = '17';
DELETE FROM tbl_cadfun
WHERE CodFun = '18';
DELETE FROM tbl_cadfun
WHERE CodFun = '20';

ALTER TABLE tbl_cadfun
ADD ADMISSAO DATE;

UPDATE tbl_cadfun
SET ADMISSAO ='01-01-2011'
WHERE codfun ='1';

UPDATE tbl_cadfun
SET ADMISSAO ='20-08-2010'
WHERE codfun ='2';

UPDATE tbl_cadfun
SET ADMISSAO ='15-01-2011'
WHERE codfun ='3';

UPDATE tbl_cadfun
SET ADMISSAO ='20-03-2014'
WHERE codfun ='4';

UPDATE tbl_cadfun
SET ADMISSAO ='02-05-2016'
WHERE codfun ='5';

UPDATE tbl_cadfun
SET ADMISSAO ='05-06-2017'
WHERE codfun ='6';

UPDATE tbl_cadfun
SET ADMISSAO ='16-02-2011'
WHERE codfun ='7';

UPDATE tbl_cadfun
SET ADMISSAO ='25-09-2014'
WHERE codfun ='8';

UPDATE tbl_cadfun
SET ADMISSAO ='09-08-2014'
WHERE codfun ='9';

UPDATE tbl_cadfun
SET ADMISSAO ='02-05-2015'
WHERE codfun ='10';

UPDATE tbl_cadfun
SET ADMISSAO ='26-01-2015'
WHERE codfun ='11';

UPDATE tbl_cadfun
SET ADMISSAO ='22-03-2013'
WHERE codfun ='12';

UPDATE tbl_cadfun
SET ADMISSAO ='15-01-2018'
WHERE codfun ='13';

UPDATE tbl_cadfun
SET ADMISSAO ='15-01-2019'
WHERE codfun ='14';

UPDATE tbl_cadfun
SET ADMISSAO ='21-01-2014'
WHERE codfun ='15';

UPDATE tbl_cadfun
SET ADMISSAO ='16-11-2016'
WHERE codfun ='16';

UPDATE tbl_cadfun
SET ADMISSAO ='15-08-2019'
WHERE codfun ='19';

UPDATE tbl_cadfun
SET ADMISSAO ='15-08-2019'
WHERE codfun ='19';

UPDATE tbl_cadfun
SET SALARIO ='5200.00'
WHERE codfun ='7';

UPDATE tbl_cadfun
SET DEPTO ='2'
WHERE NOME ='BRUNA MARQUEZINE';

UPDATE tbl_cadfun
SET FUNCAO ='ASSISTENTE'
WHERE codfun ='5';

UPDATE tbl_cadfun
SET SALARIO = SALARIO * 1.1;

SELECT MAX(SALARIO) FROM tbl_cadfun;
SELECT MIN(SALARIO) FROM tbl_cadfun;
SELECT AVG(SALARIO) FROM tbl_cadfun;
SELECT SUM(SALARIO) FROM tbl_cadfun;

SELECT DEPTO, MAX(SALARIO) AS MaiorSalario
FROM tbl_cadfun
GROUP BY DEPTO;

SELECT DEPTO, MIN(SALARIO) AS MenorSalario
FROM tbl_cadfun
GROUP BY DEPTO;

SELECT DEPTO, SUM(SALARIO) AS TotalSalario
FROM tbl_cadfun
GROUP BY DEPTO;

SELECT DEPTO, AVG(SALARIO) AS MediaSalario
FROM tbl_cadfun
GROUP BY DEPTO;

SELECT * FROM tbl_cadfun
WHERE NOME LIKE 'B%';
